#!/usr/bin/env bash

# Purpose: Always use the latest RADIOHEAD.sh from github.

curl -s https://raw.githubusercontent.com/CorentinB/radio_archiving/master/RADIOHEAD.sh?token=AN4V76-Ukif-_EmLttrq5FCU0HDCE9b9ks5bBLnYwA%3D%3D | bash
