#!/usr/bin/env bash

function _radioDL() {
  local NOW="date +'%d-%m-%Y-%H-%M-%S'"
  local THREADS="cat urls.txt | wc -l"
  for (( ; ; )); do
    echo "$THREADS"
    mkdir "$NOW"
    timeout "$1" aria2c -j "$THREADS" -i urls.txt -d "$NOW"
    rclone move "$NOW" "$2:Radio/$NOW" &
    rm -rf "$NOW"
  done
}

_radioDL "$@"
